### PR TITLE
PROJ-2107: Fix JS, remove vertical scroll bar, add cell minimization

### PR DESCRIPTION
**Pull request by VincentKetelaars**
The code is extremely hacky and ugly, but it works for now.

Code inputs and stderr is hidden by default
image

Can minimize individual cells now (ugly I know)
image

No more vertical bar.
image

Because JS is no longer crashing, we can actually see other images too now. Though there might be too many of them. And I see them in the file explorer too sometimes..
image

### CODE REVIEW

**Comment by FranktheTank123** [comment]
I will defer to @mstewart141

**Comment by ToddASmall** [comment]
This is great progress!

I don't know anything about writing good code in JavaScript. We could perhaps ask someone from one of the front-end teams to look over this PR.

**Comment by VincentKetelaars** [comment]
> This is great progress!
> 
> I don't know anything about writing good code in JavaScript. We could perhaps ask someone from one of the front-end teams to look over this PR.

I appreciate the thought. However, I would rather that nobody ever looks at this ever. I don't consider it a maintainable solution. It is however done now, and should be enough for the foreseeable future.

**Review by mstewart141 — APPROVED** [review]
thanks vincent, LGTM!! please add (liberal) comments to this code prior to merging so future us have any idea WTH is going on here 😅

**Pull request merged**
